version: "2.2"
services:
  backend:
    container_name: "backend"
    image: tpk-backend:latest
    ports:
      - "5000:5000"
    restart: on-failure
networks:
  default:
    external:
      name: project-net
