version: "2.2"
services:
  backend:
    env_file:
      - ../app/.env.dev
    container_name: "backendDev"
    image: ghcr.io/artidsun/int371-backend-dev:latest
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - /home/rmadmin/dev-images/images:/app/images
networks:
  default:
    external:
      name: project-net
