version: "2.2"
services:
  backend:
    env_file:
      - .env.dev
    container_name: "${CONTAINER_NAME}"
    image: backend-dev:latest
    ports:
      - "${COMPOSE_PORT}"
    restart: on-failure
networks:
  default:
    external:
      name: project-net
