version: "3.3"
services:
  backend:
    container_name: "backendPrd"
    image: ghcr.io/artidsun/int371-backend-prd:latest
    ports:
      - "9000:9000"
    restart: on-failure
networks:
  default:
    external:
      name: project-net
