version: "3.3"
services:
  backend:
    env_file:
      - ../app/.env.dev
    container_name: "backendPrd"
    image: ghcr.io/artidsun/int371-backend-prd:latest
    ports:
      - "5000:5000"
    restart: on-failure
    volumes:
      - /home/rmadmin/prd-images/images:/app/images
networks:
  default:
    external:
      name: project-net
