name: ci-backend-int371
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: pull images and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd tpk-Backend
            git checkout dev
            git pull origin dev
            cd script/Docker-dev
            docker rm -f backend-dev
            docker rmi backend-dev:latest
            docker build . -t backend-dev:latest
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: pull images and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd tpk-Backend/script/Docker-dev
            docker-compose up -d
  CheckHealthy:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Check health check page
        run: curl https://rungmod.ddns.net/api/checkHealthy | grep "Healthy"