name: ci-backend-int371
on:
  push:
    branches:
      - prd
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: PRD/Dockerfile
          push: true
          tags: ghcr.io/artidsun/int371-backend-prd:latest
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: pull images and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd tpk-Backend
            git pull
            git checkout prd
            git pull origin prd
            docker rm -f backendPrd
            docker rmi ghcr.io/artidsun/int371-backend-prd:latest
            docker pull ghcr.io/artidsun/int371-backend-prd:latest
            cd PRD
            docker-compose up -d
  CheckHealthy:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Check health check page
        run: curl https://www.rungmod.com/api/checkHealthy | grep "Healthy"
